[build]
  base = "web"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/reports"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reports/*"
  to = "/index.html"
  status = 200
